name: expector
description: A package to write tests in a fluent manner and more easily.
version: 0.1.3
homepage: https://github.com/a14n/dart-expector

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  test: ^1.17.3

dev_dependencies:
  lints: ^2.0.1
