name: expector
description: A package to write tests in a fluent manner and more easily.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta:

dev_dependencies:
  pedantic:
  test:
